> Numpy基础
> - Written by leiding

In [1]:
import numpy as np

In [2]:
# 1. ndarray与list计算时间比较
my_arr = np.arange(1000000)
my_list = list(range(1000000))
%time for _ in range(10): my_arr2 = my_arr * 2
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: total: 0 ns
Wall time: 11 ms
CPU times: total: 328 ms
Wall time: 502 ms


In [3]:
# 2. 认识ndarray
data = np.random.randn(2, 3)
print(type(data))
print(data.ndim)
print(data.shape)
print(data.size)
print(data.dtype)
print(data.itemsize)
data

<class 'numpy.ndarray'>
2
(2, 3)
6
float64
8


array([[-0.43317712, -1.86883417, -0.28525647],
       [-0.74608921,  0.61256732,  1.02325742]])

In [4]:
# 3. array函数
data1 = np.array([1, 2, 3])
data2 = np.array([[1, 2, 3], [4, 5, 6]])
# data3 = np.array([[1, 2, 3], [4, 5]])
data4 = np.array([[1, 2, 3], [4, 5, 6]], dtype='float32')
# data4 = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)
print(data1)
print(data2, data2.dtype)
print(data4, data4.dtype.name)

[1 2 3]
[[1 2 3]
 [4 5 6]] int32
[[1. 2. 3.]
 [4. 5. 6.]] float32


In [5]:
# 4. 其他生成数组的方法1
print(np.zeros((3, 4)))
print(np.ones((3, 4, 5)))
print(np.empty((3, 4)))
print(np.arange(1, 20, 5))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[ 1  6 11 16]


In [6]:
# 5. asarray与array
x = [1, 2, 3]
a = np.array(x)
b = np.array(a)
c = np.asarray(a)
d = np.asarray(x)
print(id(x), id(a), id(b), id(c), id(d))

1373285362304 1373305384848 1373391078960 1373305384848 1373391079056


In [7]:
# 6. 其他生成数组的方法2
x = np.array([[1, 2, 3], [4, 5, 6]])
print(np.ones_like(x))
print(np.zeros_like(x))
print(np.empty_like(x))
print(np.full((3, 2), 9))
print(np.full_like(x, 9))
print(np.eye(4))
print(np.identity(4))

[[1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]]
[[9 9]
 [9 9]
 [9 9]]
[[9 9 9]
 [9 9 9]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
# 7. 数据类型转换
data = np.array([[1, 2, 3], [4, 5, 6.6]])
data1 = data.astype(int)
# data1 = data.astype(np.float64)
data1

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
# 8. 数组算术
data1 = np.array([[1, 2, 3], [4, 5, 6]])
data2 = np.array([[7, 8, 9], [10, 11, 12]])
print(data1 + data2)
print(data1 - data2)
print(data1 * data2)
print(data1 / data2)
print(data1 > data2)
print(1 / data1)
print(data1 ** 0.5)

[[ 8 10 12]
 [14 16 18]]
[[-6 -6 -6]
 [-6 -6 -6]]
[[ 7 16 27]
 [40 55 72]]
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]
[[False False False]
 [False False False]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [10]:
# 9. 一维数组的索引与切片
arr = np.arange(10)
print(arr)
arr_slice = arr[1:7:2]
print(arr_slice)
arr_slice[0] = 999
print(arr)
arr_slice[:] = 888
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5]
[  0 999   2   3   4   5   6   7   8   9]
[  0 888   2 888   4 888   6   7   8   9]


In [11]:
# 10. 拷贝与视图
a = np.arange(12)
b = a  # 完全不拷贝
print(b is a)  # True

c = a.view()  # 视图（浅拷贝）
print(c is a)  # False
print(c.base is a)  # True
c[4] = 999
print(a)

s = a[1:6]  # 切片是一种视图
s[:] = 888
print(a)

d = a.copy()  # 深拷贝
print(d is a)  # False
print(d.base is a)  # False
d[4] = 777
print(a)

True
False
True
[  0   1   2   3 999   5   6   7   8   9  10  11]
[  0 888 888 888 888 888   6   7   8   9  10  11]
False
False
[  0 888 888 888 888 888   6   7   8   9  10  11]


In [12]:
# 11. 二维数组的索引与切片
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d)
print(arr2d[0][2], arr2d[0, 2])
print(arr2d[::2, ::-1])
print(arr2d[2], arr2d[:, 2], arr2d[:, 2:])
arr2d[:,2] = 44
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3 3
[[3 2 1]
 [9 8 7]]
[7 8 9] [3 6 9] [[3]
 [6]
 [9]]
[[ 1  2 44]
 [ 4  5 44]
 [ 7  8 44]]


In [13]:
# 12. 更高维数组的索引与切片
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print('arr3d =', arr3d)
print('\narr3d[0] = ', arr3d[0])
arr3d[0] = 42
# arr3d[0] = np.array([42, 43])  # ValueError
# arr3d[0] = np.array([42, 43, 44])
print('\narr3d =', arr3d)
print('\narr3d[1, 0] = ', arr3d[1, 0])

arr3d = [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

arr3d[0] =  [[1 2 3]
 [4 5 6]]

arr3d = [[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]

arr3d[1, 0] =  [7 8 9]


In [14]:
# 13. 布尔索引
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(data)
print('\n', names == 'Bob')
print('\n', data[names == 'Bob'])
print('\n', data[(names == 'Bob') | (names == 'Will')])
data[data < 0] = 0
print('\n', data)

[[-0.10761356 -1.93179692  0.74193782  0.08582662]
 [ 0.39832244 -1.74615376 -0.38440064  0.68525014]
 [-0.63330856 -1.26265699  1.61995879  0.71231052]
 [ 0.76215889 -0.66692113 -0.43101155 -0.32746655]
 [ 0.64155467  0.49858951  0.65463833  0.43469036]
 [-0.89091222 -0.15293795  0.17599438  0.05147642]
 [ 0.92873179 -0.3310033  -0.15182514 -1.42201282]]

 [ True False False  True False False False]

 [[-0.10761356 -1.93179692  0.74193782  0.08582662]
 [ 0.76215889 -0.66692113 -0.43101155 -0.32746655]]

 [[-0.10761356 -1.93179692  0.74193782  0.08582662]
 [-0.63330856 -1.26265699  1.61995879  0.71231052]
 [ 0.76215889 -0.66692113 -0.43101155 -0.32746655]
 [ 0.64155467  0.49858951  0.65463833  0.43469036]]

 [[0.         0.         0.74193782 0.08582662]
 [0.39832244 0.         0.         0.68525014]
 [0.         0.         1.61995879 0.71231052]
 [0.76215889 0.         0.         0.        ]
 [0.64155467 0.49858951 0.65463833 0.43469036]
 [0.         0.         0.17599438 0.05147642]


In [15]:
# 14. 神奇索引
arr = np.arange(4)
arr = arr + np.arange(8).reshape(8, 1) * 10
# arr = np.tile(np.arange(4), (8, 1)) + np.tile(np.arange(8) * 10, (4, 1)).T

print(arr)
print('\n', arr[[4, 3, 0, 6]])
print('\n', arr[[-3, 5, -7]])
print('\n', arr[[1, 5, 7, 2], [2, 3, 2, 2]])

arr[5:1:-1, [2, 2]]

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]
 [50 51 52 53]
 [60 61 62 63]
 [70 71 72 73]]

 [[40 41 42 43]
 [30 31 32 33]
 [ 0  1  2  3]
 [60 61 62 63]]

 [[50 51 52 53]
 [50 51 52 53]
 [10 11 12 13]]

 [12 53 72 22]


array([[52, 52],
       [42, 42],
       [32, 32],
       [22, 22]])

In [16]:
# 15. 二维数组的转置
arr = np.arange(15).reshape(3, -1)
print(arr, arr.shape)
# print('\n', arr.transpose())
print('\n', arr.T, arr.T.shape)
print('\n', np.dot(arr.T, arr))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] (3, 5)

 [[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]] (5, 3)

 [[125 140 155 170 185]
 [140 158 176 194 212]
 [155 176 197 218 239]
 [170 194 218 242 266]
 [185 212 239 266 293]]


In [17]:
# 16. 高维数组的转置和换轴
arr = np.arange(16).reshape((2, 2, 4))
print(arr, arr.shape)
print('\n', arr.transpose(1, 0 ,2))
print('\n', arr.swapaxes(1, 2))
print('\n', arr.T, arr.T.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] (2, 2, 4)

 [[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]

 [[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]

 [[[ 0  8]
  [ 4 12]]

 [[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]] (4, 2, 2)


In [18]:
# 17. 通用函数
x = np.array([12, 9, 13, 15])
y = np.array([11, 10, 4, 8])
print(np.sqrt(x))
print(np.modf(np.sqrt(x)))
print(np.square(x))
print(np.add(x, y))
print(np.multiply(x, y))
print(np.maximum(x, y))
print(np.greater(x, y))
print(x > y)

z = np.empty((2, 4))
print(np.square(x, out=z))

[3.46410162 3.         3.60555128 3.87298335]
(array([0.46410162, 0.        , 0.60555128, 0.87298335]), array([3., 3., 3., 3.]))
[144  81 169 225]
[23 19 17 23]
[132  90  52 120]
[12 10 13 15]
[ True False  True  True]
[ True False  True  True]
[[144.  81. 169. 225.]
 [144.  81. 169. 225.]]


In [19]:
# 18. 将条件逻辑转为数组运算：where
arr_x = np.array([1, 5, 7])
arr_y = np.array([2, 6, 8])
arr_con = np.array([True, False, True])
print(np.where(arr_con, arr_x, arr_y))
# print([(x if c else y) for x, y, c in zip(arr_x, arr_y, arr_con)])

arr = np.random.randn(4, 4)
print('\n', arr)
print('\n', np.where(arr > 0 , 2, arr))

[1 6 7]

 [[-1.98428575  0.45173916 -1.19560307 -0.1566512 ]
 [ 1.11406026  0.53538305  0.57299385 -0.98348503]
 [ 0.83644057 -1.24126124 -0.10608717 -1.19280275]
 [ 0.18559417  0.53094494  0.76887982  1.2011706 ]]

 [[-1.98428575  2.         -1.19560307 -0.1566512 ]
 [ 2.          2.          2.         -0.98348503]
 [ 2.         -1.24126124 -0.10608717 -1.19280275]
 [ 2.          2.          2.          2.        ]]


In [20]:
# 19. 数组统计运算
arr = np.random.randn(5, 4)
print(arr)
print('\n', arr.mean(), np.mean(arr), arr.sum())
print('\n', arr.mean(1))
print('\n', arr.sum(0))

brr = np.arange(9).reshape(3, -1)
print('\n', brr)
print('\n', brr.cumsum(axis=0))
print('\n', brr.cumprod(1))

[[ 2.18368948  0.74794768 -1.02389487  0.30652607]
 [ 1.99164858  0.40688095  0.48183963  0.5194605 ]
 [-0.13851623 -1.51074343 -0.10212625  0.03196218]
 [ 0.73349192  0.7922283   0.93397306  0.76741721]
 [-0.14257809 -0.20184476 -0.27118207  1.19745292]]

 0.3851816387295629 0.3851816387295629 7.7036327745912585

 [ 0.55356709  0.84995741 -0.42985593  0.80677762  0.145462  ]

 [4.62773565 0.23446874 0.0186095  2.82281888]

 [[0 1 2]
 [3 4 5]
 [6 7 8]]

 [[ 0  1  2]
 [ 3  5  7]
 [ 9 12 15]]

 [[  0   0   0]
 [  3  12  60]
 [  6  42 336]]


In [21]:
# 20. 检索数组元素
arr = np.random.rand(100)
print((arr > .5).sum())

brr = np.array([[1, -2, -7], [-3, 6, 2], [-4, 3, 2]])
print(np.any(brr > 0))
print(np.all(brr > 0))

49
True
False


In [22]:
# 21. 数组排序
arr = np.random.randn(5, 3)
print(arr)
arr.sort()
print('\n', arr)

brr = np.random.randn(5, 3)
print('\n', brr)
print('\n', np.sort(brr, 0))

[[-0.90470056  0.1074987   1.22494439]
 [ 1.63921567  0.60243947 -0.43855524]
 [ 1.7691673   1.43007935  2.30770231]
 [ 0.51563216 -0.73431499 -0.48009226]
 [-0.11259896 -0.44337041  1.17472392]]

 [[-0.90470056  0.1074987   1.22494439]
 [-0.43855524  0.60243947  1.63921567]
 [ 1.43007935  1.7691673   2.30770231]
 [-0.73431499 -0.48009226  0.51563216]
 [-0.44337041 -0.11259896  1.17472392]]

 [[-0.27006049  0.99272132 -0.36030248]
 [-0.64221117  0.2405588   0.11437874]
 [ 0.20898362  1.25454979  0.95240657]
 [-0.34162999  0.94301009  0.51935845]
 [-1.17509745 -1.19062103 -0.80949402]]

 [[-1.17509745 -1.19062103 -0.80949402]
 [-0.64221117  0.2405588  -0.36030248]
 [-0.34162999  0.94301009  0.11437874]
 [-0.27006049  0.99272132  0.51935845]
 [ 0.20898362  1.25454979  0.95240657]]


In [23]:
# 22. 集合逻辑
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(np.unique(names))

values = np.array([6, 0, 0, 3, 2, 5, 6])
print(np.in1d(values, [2, 3, 6]))

['Bob' 'Joe' 'Will']
[ True False False  True  True False  True]


In [24]:
# 23. 线性代数运算
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a * a)
print('\n', np.multiply(a, a))
print('\n', np.dot(a, a))
print('\n', a.dot(a))
print('\n', np.inner(a, a))
print('\n', np.inner(a, a.T))
print('\n', np.outer(a, a))

print('\n', np.diag(a))
print('\n', np.diag(np.diag(a)))
print('\n', np.linalg.det(a))

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]

 [[ 1  4  9]
 [16 25 36]
 [49 64 81]]

 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]

 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]

 [[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]

 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]

 [[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]

 [1 5 9]

 [[1 0 0]
 [0 5 0]
 [0 0 9]]

 -9.51619735392994e-16


In [25]:
# 24. 随机数
a = np.arange(50, 60)
print(np.random.permutation(a))
print(np.random.permutation(10))
np.random.shuffle(a)
print(a)

print('\n', np.random.rand(4, 3))
print('\n', np.random.randint(10, 120, size=(4, 3)))
print('\n', np.random.randint([10, 100], 120))
print('\n', np.random.randn(4, 3))
print('\n', np.random.uniform(10, 15, size=(4, 3)))

[50 54 55 53 59 57 51 58 52 56]
[0 5 8 7 6 4 3 2 1 9]
[57 58 54 52 56 53 51 55 50 59]

 [[0.30000123 0.45855719 0.73957314]
 [0.80361912 0.41184493 0.80683625]
 [0.43716879 0.20960453 0.6995084 ]
 [0.89719486 0.05763512 0.55593209]]

 [[ 15  19  60]
 [ 17  43  23]
 [119  13  18]
 [ 58 105  75]]

 [ 92 100]

 [[-0.33098939  0.79347657  0.00783611]
 [-0.08968108 -0.72651764 -0.03214385]
 [ 0.46804989  0.08114233  1.93633671]
 [ 0.78374354 -0.76973907 -1.28863866]]

 [[12.44443997 11.63434885 12.11293013]
 [11.18381074 11.96998715 12.35176487]
 [14.02194532 12.83401686 13.23972313]
 [11.50514934 10.81072511 11.16798381]]


In [26]:
# 25. 随机漫步1：原生Python方法
import random
position = 0
walk = [position]
steps = 1000
for i in range(steps):
    step = 1 if random.randint(0, 1) else -1
    position += step
    walk.append(position)
print(walk)

[0, -1, -2, -3, -2, -3, -2, -1, -2, -1, 0, -1, 0, -1, 0, -1, 0, -1, 0, 1, 0, 1, 0, -1, -2, -1, -2, -3, -2, -1, 0, -1, 0, 1, 2, 1, 0, -1, -2, -3, -4, -5, -6, -5, -4, -3, -2, -3, -4, -5, -4, -5, -4, -5, -4, -3, -4, -5, -4, -5, -6, -5, -4, -5, -6, -5, -4, -3, -2, -3, -2, -1, 0, 1, 0, -1, -2, -1, 0, -1, 0, 1, 2, 3, 4, 5, 4, 3, 2, 3, 2, 1, 0, -1, -2, -1, -2, -3, -2, -1, -2, -1, 0, -1, 0, 1, 2, 1, 0, 1, 0, -1, -2, -3, -4, -3, -2, -3, -2, -1, 0, -1, -2, -3, -4, -3, -2, -3, -2, -3, -2, -3, -2, -1, 0, 1, 2, 1, 2, 3, 2, 1, 0, 1, 0, -1, -2, -1, 0, -1, -2, -1, -2, -3, -2, -1, 0, 1, 2, 1, 0, 1, 2, 1, 2, 1, 0, 1, 0, -1, -2, -1, 0, 1, 2, 1, 0, 1, 2, 3, 2, 3, 4, 3, 2, 3, 2, 1, 0, -1, -2, -3, -4, -3, -4, -5, -4, -5, -6, -5, -6, -7, -8, -7, -6, -5, -6, -5, -6, -5, -4, -5, -4, -3, -2, -3, -4, -5, -4, -5, -6, -7, -8, -7, -6, -5, -4, -5, -6, -5, -4, -3, -2, -1, -2, -1, 0, 1, 0, 1, 2, 1, 0, 1, 0, -1, 0, 1, 0, 1, 2, 1, 0, -1, 0, -1, 0, 1, 0, 1, 0, 1, 0, 1, 2, 3, 2, 3, 2, 1, 0, -1, 0, 1, 2, 3, 2, 1, 2, 1, 2, 

In [27]:
# 26. 随机漫步2：numpy
nsteps = 1000
draws = np.random.randint(0, 2, size=nsteps)
steps = np.where(draws > 0, 1, -1)
walk = steps.cumsum()
print(walk)

[  1   2   1   2   1   0  -1   0  -1   0  -1   0   1   0   1   0  -1  -2
  -3  -4  -3  -2  -3  -2  -3  -4  -5  -4  -3  -2  -1  -2  -3  -4  -5  -6
  -5  -6  -7  -6  -5  -4  -3  -2  -1  -2  -1  -2  -3  -2  -1   0  -1  -2
  -3  -2  -3  -4  -3  -4  -3  -4  -3  -2  -1  -2  -3  -4  -3  -2  -3  -2
  -1  -2  -1  -2  -1   0   1   2   3   2   1   0   1   0   1   0  -1  -2
  -1  -2  -1  -2  -1   0   1   0  -1  -2  -3  -4  -3  -2  -3  -2  -1   0
   1   2   1   0  -1  -2  -3  -4  -3  -4  -5  -6  -7  -6  -5  -6  -5  -6
  -7  -8  -9 -10  -9  -8  -9  -8  -9  -8  -7  -6  -5  -6  -7  -8  -7  -8
  -7  -8  -7  -8  -7  -8  -7  -8  -7  -8  -9  -8  -9 -10  -9 -10  -9  -8
  -7  -8  -9 -10 -11 -12 -11 -10  -9 -10  -9  -8  -9  -8  -7  -8  -9  -8
  -7  -8  -9  -8  -7  -8  -9  -8  -9  -8  -9 -10 -11 -12 -13 -12 -13 -12
 -11 -10  -9 -10 -11 -12 -11 -12 -11 -10 -11 -10  -9  -8  -9  -8  -7  -8
  -7  -8  -9  -8  -9  -8  -7  -6  -7  -6  -5  -6  -5  -6  -7  -8  -9 -10
 -11 -10  -9 -10  -9 -10  -9  -8  -7  -6  -5  -6  -

In [28]:
# 27. 随机漫步3: 统计
print(walk.min(), walk.max())
(np.abs(walk) >= 30).argmax()

-21 18


0

In [29]:
# 28. 随机漫步4: 多次模拟
nwalks = 5000
nsteps = 1000
draws = np.random.randint(0, 2, size=(nwalks, nsteps))
steps = np.where(draws > 0, 1, -1)
walks = steps.cumsum(axis=1)
print(walks)

[[ -1   0   1 ... -58 -59 -58]
 [ -1  -2  -3 ...  -4  -3  -4]
 [ -1  -2  -3 ...  36  37  36]
 ...
 [ -1  -2  -1 ... -18 -17 -16]
 [  1   2   3 ... -46 -45 -44]
 [  1   2   3 ...  30  31  30]]


In [30]:
# 29. 随机漫步5:多次模拟的统计
print(walks.max(), walks.min())
print((np.abs(walks) >= 30).any(axis=1).sum())
print((np.abs(walks) >= 30).argmax(axis=1).mean())

134 -108
3364
339.4088
